-- 1. Table Users
CREATE TABLE public.user (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'staff',
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_pkey PRIMARY KEY (id)
);

-- 2. Table Categories
CREATE TABLE public.category (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name character varying NOT NULL,
  description text,
  icon character varying NOT NULL DEFAULT 'fas fa-tags',
  CONSTRAINT category_pkey PRIMARY KEY (id)
);

-- 3. Table Products
CREATE TABLE public.product (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name character varying NOT NULL,
  price integer NOT NULL,
  description text,
  stock integer NOT NULL DEFAULT 0,

  sku character varying,
  image_url character varying,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),

  category_id integer,
  CONSTRAINT product_pkey PRIMARY KEY (id),
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES public.category(id) ON DELETE SET NULL
);